const problems = [
  { id:`E01`, type:`fill_blank`, difficulty:`easy`, title:`변수 선언`,
    question:`_____ x = 10; System.out.println(x);`,
    answer:{ JAVA:["int"], PYTHON:["int"], CPP:["int"] },
    options:null, correctIndex:null,
    explanation:`정수형 변수를 선언할 때 int 키워드를 사용합니다.` },
  { id:`E02`, type:`multiple_choice`, difficulty:`easy`, title:`반복문 키워드`,
    question:`0부터 4까지 반복하는 반복문의 키워드는?`,
    answer:{ JAVA:["for"], PYTHON:["for"], CPP:["for"] },
    options:["for", "while", "if", "switch"], correctIndex:0,
    explanation:`for(초기값;조건;증감)은 가장 기본적인 반복문입니다.` },
  { id:`E03`, type:`short_answer`, difficulty:`easy`, title:`출력값`,
    question:`System.out.println(1+2); 의 출력값은? (숫자만 입력)`,
    answer:{ JAVA:["3"], PYTHON:["3"], CPP:["3"] },
    options:null, correctIndex:null,
    explanation:`1과 2를 더한 값 3이 출력됩니다.` },
  { id:`E04`, type:`fill_blank`, difficulty:`easy`, title:`논리 NOT`,
    question:`boolean flag = false; if (!_____) { System.out.println("참"); }`,
    answer:{ JAVA:["flag"], PYTHON:["flag"], CPP:["flag"] },
    options:null, correctIndex:null,
    explanation:`논리 NOT(!)으로 false를 반전시킵니다.` },
  { id:`E05`, type:`multiple_choice`, difficulty:`easy`, title:`주석 기호`,
    question:`Java와 C++에서 한 줄 주석을 표시하는 기호는?`,
    answer:{ JAVA:["//"], PYTHON:["#"], CPP:["//"] },
    options:["//", "#", "/**", "--"], correctIndex:0,
    explanation:`Java/C++은 //로, Python은 #으로 한 줄 주석을 만듭니다.` },
  { id:`E06`, type:`short_answer`, difficulty:`easy`, title:`증가 결과`,
    question:`int x = 5; x++; System.out.println(x); 의 출력값은? (숫자만)`,
    answer:{ JAVA:["6"], PYTHON:["6"], CPP:["6"] },
    options:null, correctIndex:null,
    explanation:`x++는 후위 증가로, x에 1을 더한 값 6이 출력됩니다.` },
  { id:`E07`, type:`fill_blank`, difficulty:`easy`, title:`논리 AND`,
    question:`if (a > 0 _____ b > 0) { ... }`,
    answer:{ JAVA:["&&"], PYTHON:["and"], CPP:["&&"] },
    options:null, correctIndex:null,
    explanation:`Java/C++은 &&, Python은 and 키워드를 사용합니다.` },
  { id:`E08`, type:`multiple_choice`, difficulty:`easy`, title:`출력 함수`,
    question:`Python에서 화면에 출력하는 함수는?`,
    answer:{ JAVA:["System.out.println"], PYTHON:["print"], CPP:["cout"] },
    options:["print", "echo", "cout", "write"], correctIndex:0,
    explanation:`Python은 print() 함수를 사용합니다.` },
  { id:`E09`, type:`short_answer`, difficulty:`easy`, title:`문자열 합`,
    question:`"Hello" + "World" 의 결과는? (따옴표 없이 한단어로)`,
    answer:{ JAVA:["HelloWorld"], PYTHON:["HelloWorld"], CPP:["HelloWorld"] },
    options:null, correctIndex:null,
    explanation:`+ 연산자는 두 문자열을 연결합니다.` },
  { id:`E10`, type:`fill_blank`, difficulty:`easy`, title:`return문`,
    question:`int add(int a, int b) { _____ a + b; }`,
    answer:{ JAVA:["return"], PYTHON:["return"], CPP:["return"] },
    options:null, correctIndex:null,
    explanation:`함수 결과를 반환할 때 return 키워드를 사용합니다.` },
  { id:`E11`, type:`fill_blank`, difficulty:`easy`, title:`문자형 변수`,
    question:`_____ c = \`A\`; // 문자 한 글자를 저장할 때`,
    answer:{ JAVA:["char"], PYTHON:["str"], CPP:["char"] },
    options:null, correctIndex:null,
    explanation:`문자 한 글자는 char 타입을 사용합니다.` },
  { id:`E12`, type:`multiple_choice`, difficulty:`easy`, title:`조건문`,
    question:`조건에 따라 실행 흐름을 나누는 키워드는?`,
    answer:{ JAVA:["if"], PYTHON:["if"], CPP:["if"] },
    options:["if", "for", "while", "switch"], correctIndex:0,
    explanation:`if문은 조건이 참일 때 코드 블록을 실행합니다.` },
  { id:`E13`, type:`fill_blank`, difficulty:`easy`, title:`반복문 종료`,
    question:`for (int i=0; i<10; i++) { if (i==5) _____; } // 반복 즉시 종료`,
    answer:{ JAVA:["break"], PYTHON:["break"], CPP:["break"] },
    options:null, correctIndex:null,
    explanation:`break는 현재 반복문을 즉시 종료합니다.` },
  { id:`E14`, type:`multiple_choice`, difficulty:`easy`, title:`참거짓 자료형`,
    question:`true/false를 저장하는 자료형은?`,
    answer:{ JAVA:["boolean"], PYTHON:["bool"], CPP:["bool"] },
    options:["int", "char", "boolean", "float"], correctIndex:2,
    explanation:`논리값 true/false는 boolean 타입을 사용합니다.` },
  { id:`E15`, type:`fill_blank`, difficulty:`easy`, title:`다음 반복`,
    question:`for (int i=0; i<10; i++) { if (i%2==0) _____; } // 다음 반복으로 건너뛰기`,
    answer:{ JAVA:["continue"], PYTHON:["continue"], CPP:["continue"] },
    options:null, correctIndex:null,
    explanation:`continue는 현재 반복을 건너뛰고 다음 반복으로 갑니다.` },
  { id:`E16`, type:`multiple_choice`, difficulty:`easy`, title:`클래스 선언`,
    question:`Java에서 클래스를 선언할 때 사용하는 키워드는?`,
    answer:{ JAVA:["class"], PYTHON:["class"], CPP:["class"] },
    options:["function", "class", "struct", "object"], correctIndex:1,
    explanation:`class 키워드로 클래스를 정의합니다.` },
  { id:`E17`, type:`fill_blank`, difficulty:`easy`, title:`객체 생성`,
    question:`Scanner sc = _____ Scanner(System.in); // 새 객체 생성`,
    answer:{ JAVA:["new"], PYTHON:["new"], CPP:["new"] },
    options:null, correctIndex:null,
    explanation:`new 키워드로 클래스의 인스턴스를 생성합니다.` },
  { id:`E18`, type:`multiple_choice`, difficulty:`easy`, title:`메소드 접근제어`,
    question:`모든 클래스에서 접근 가능한 접근 제어자는?`,
    answer:{ JAVA:["public"], PYTHON:["public"], CPP:["public"] },
    options:["private", "protected", "public", "default"], correctIndex:2,
    explanation:`public은 어디서든 접근할 수 있습니다.` },
  { id:`E19`, type:`fill_blank`, difficulty:`easy`, title:`정적 메소드`,
    question:`public _____ void main(String[] args) { ... } // 객체 생성 없이 호출`,
    answer:{ JAVA:["static"], PYTHON:["@staticmethod"], CPP:["static"] },
    options:null, correctIndex:null,
    explanation:`static 메소드는 클래스 레벨에서 동작합니다.` },
  { id:`E20`, type:`multiple_choice`, difficulty:`easy`, title:`예외 처리`,
    question:`예외를 처리하는 키워드 쌍은?`,
    answer:{ JAVA:["try-catch"], PYTHON:["try-except"], CPP:["try-catch"] },
    options:["if-else", "try-catch", "for-while", "switch-case"], correctIndex:1,
    explanation:`try-catch 블록으로 예외를 처리합니다.` },
  { id:`X01`, type:`fill_blank`, difficulty:`easy`, title:`논리 OR`,
    question:`if (a > 0 _____ b > 0) { ... } // 둘 중 하나라도 참이면 실행`,
    answer:{ JAVA:["||"], PYTHON:["or"], CPP:["||"] },
    options:null, correctIndex:null,
    explanation:`논리 OR는 Java/C++에서 ||, Python에서 or 입니다.` },
  { id:`X02`, type:`multiple_choice`, difficulty:`easy`, title:`switch-case`,
    question:`switch문에서 모든 case 이후에 실행되는 키워드는?`,
    answer:{ JAVA:["default"], PYTHON:["else"], CPP:["default"] },
    options:["default", "else", "break", "continue"], correctIndex:0,
    explanation:`switch문의 기본 처리는 default입니다.` },
  { id:`X03`, type:`fill_blank`, difficulty:`easy`, title:`상속`,
    question:`class Dog _____ Animal { ... } // 부모 클래스 상속`,
    answer:{ JAVA:["extends"], PYTHON:["(Animal)"], CPP:[": public"] },
    options:null, correctIndex:null,
    explanation:`Java는 extends, Python은 클래스 인자, C++은 : public을 사용합니다.` },
  { id:`X04`, type:`multiple_choice`, difficulty:`easy`, title:`인터페이스`,
    question:`Java에서 인터페이스를 구현할 때 사용하는 키워드는?`,
    answer:{ JAVA:["implements"], PYTHON:["implements"], CPP:["implements"] },
    options:["extends", "implements", "inherit", "override"], correctIndex:1,
    explanation:`인터페이스 구현은 implements를 사용합니다.` },
  { id:`X05`, type:`fill_blank`, difficulty:`easy`, title:`throw`,
    question:`throw new _____Exception("에러"); // 예외 발생`,
    answer:{ JAVA:["IllegalArgument"], PYTHON:["Value"], CPP:["runtime"] },
    options:null, correctIndex:null,
    explanation:`throw로 예외를 던집니다.` },
  { id:`X06`, type:`multiple_choice`, difficulty:`easy`, title:`final`,
    question:`변수를 상수처럼 변경 불가능하게 만드는 키워드는?`,
    answer:{ JAVA:["final"], PYTHON:["final"], CPP:["const"] },
    options:["static", "final", "const", "immutable"], correctIndex:1,
    explanation:`Java/C++은 final/const로 변경을 막습니다.` },
  { id:`X07`, type:`fill_blank`, difficulty:`easy`, title:`패키지`,
    question:`_____ java.util.Scanner; // 외부 클래스를 가져올 때`,
    answer:{ JAVA:["import"], PYTHON:["import"], CPP:["#include"] },
    options:null, correctIndex:null,
    explanation:`import로 패키지를 가져옵니다.` },
  { id:`X08`, type:`multiple_choice`, difficulty:`easy`, title:`this`,
    question:`현재 객체를 가리키는 키워드는?`,
    answer:{ JAVA:["this"], PYTHON:["self"], CPP:["this"] },
    options:["this", "self", "me", "current"], correctIndex:0,
    explanation:`Java/C++은 this, Python은 self를 사용합니다.` },
  { id:`X09`, type:`fill_blank`, difficulty:`easy`, title:`switch-case`,
    question:`switch (n) { case 1: _____; case 2: ... } // case 실행 후 다음 case로 넘어가지 않게`,
    answer:{ JAVA:["break"], PYTHON:["break"], CPP:["break"] },
    options:null, correctIndex:null,
    explanation:`break로 case를 탈출합니다.` },
  { id:`X10`, type:`multiple_choice`, difficulty:`easy`, title:`void`,
    question:`값을 반환하지 않는 메소드의 반환 타입은?`,
    answer:{ JAVA:["void"], PYTHON:["None"], CPP:["void"] },
    options:["int", "void", "null", "None"], correctIndex:1,
    explanation:`void는 반환값이 없음을 의미합니다.` },
  { id:`M01`, type:`fill_blank`, difficulty:`medium`, title:`배열 길이`,
    question:`int[] arr = {3, 1, 4, 1, 5};
for (int i = 0; i < arr._____; i++) { ... }`,
    answer:{ JAVA:["length"], PYTHON:["len(arr)"], CPP:["size()"] },
    options:null, correctIndex:null,
    explanation:`배열을 순회할 때는 length/len/size를 사용합니다.` },
  { id:`M02`, type:`fill_blank`, difficulty:`medium`, title:`소수 판별`,
    question:`int n = 11;
boolean isPrime = true;
for (int i = 2; i < n; i++) {
    if (n % i == _____) { isPrime = _____; break; }
}`,
    answer:{ JAVA:["0", "false"], PYTHON:["0", "False"], CPP:["0", "false"] },
    options:null, correctIndex:null,
    explanation:`2부터 n-1까지 나누어 떨어지면 소수가 아닙니다.` },
  { id:`M03`, type:`multiple_choice`, difficulty:`medium`, title:`버블정렬 1회전`,
    question:`int[] a = {5, 2, 8, 1, 3}을 버블정렬(오름차순) 1회전 후 배열 상태는?`,
    answer:{ JAVA:["2,5,1,3,8"], PYTHON:["2,5,1,3,8"], CPP:["2,5,1,3,8"] },
    options:["2,5,1,3,8", "1,2,3,5,8", "5,2,8,1,3", "8,5,3,2,1"], correctIndex:0,
    explanation:`버블정렬 1회전 시 가장 큰 값(8)이 맨 뒤로 이동합니다.` },
  { id:`M04`, type:`fill_blank`, difficulty:`medium`, title:`팩토리얼`,
    question:`int n = 5;
int result = 1;
for (int i = _____; i <= n; i++) {
    result _____= i;
}`,
    answer:{ JAVA:["2", "*"], PYTHON:["2", "*"], CPP:["2", "*"] },
    options:null, correctIndex:null,
    explanation:`1부터 n까지의 곱. 2부터 n까지 차례대로 곱합니다.` },
  { id:`M05`, type:`fill_blank`, difficulty:`medium`, title:`문자열 뒤집기`,
    question:`String s = "hello";
String rev = "";
for (int i = s._____() - 1; i >= 0; i_____) {
    rev += s.charAt(i);
}`,
    answer:{ JAVA:["length", "--"], PYTHON:["len", " -= 1"], CPP:["length", "--"] },
    options:null, correctIndex:null,
    explanation:`문자열 끝에서부터 한 글자씩 가져와 새 문자열을 만듭니다.` },
  { id:`M06`, type:`short_answer`, difficulty:`medium`, title:`이진수 변환`,
    question:`10진수 13을 2진수로 변환한 값은? (숫자만)`,
    answer:{ JAVA:["1101"], PYTHON:["1101"], CPP:["1101"] },
    options:null, correctIndex:null,
    explanation:`13 = 8+4+1 = 1101₂` },
  { id:`M07`, type:`multiple_choice`, difficulty:`medium`, title:`while 반복 횟수`,
    question:`int i=0; while(i<10) { i+=2; } 반복문은 몇 번 실행되나요?`,
    answer:{ JAVA:["5"], PYTHON:["5"], CPP:["5"] },
    options:["5", "10", "6", "4"], correctIndex:0,
    explanation:`i값: 0→2→4→6→8→10(종료). 총 5번 실행됩니다.` },
  { id:`M08`, type:`short_answer`, difficulty:`medium`, title:`문자열 replace`,
    question:`String s = "aabbcc"; s.replace("a","x")의 결과는?`,
    answer:{ JAVA:["xxbbcc"], PYTHON:["xxbbcc"], CPP:["xxbbcc"] },
    options:null, correctIndex:null,
    explanation:`replace()는 모든 일치하는 문자를 대체합니다.` },
  { id:`M09`, type:`multiple_choice`, difficulty:`medium`, title:`피보나치`,
    question:`피보나치 수열 0,1,1,2,3,5,... 의 6번째(0-index) 값은?`,
    answer:{ JAVA:["8"], PYTHON:["8"], CPP:["8"] },
    options:["5", "8", "13", "6"], correctIndex:1,
    explanation:`0→1→1→2→3→5→8. 6번째는 8입니다.` },
  { id:`M10`, type:`short_answer`, difficulty:`medium`, title:`배열 합계`,
    question:`int[] a = {2,4,6,8}; 모든 요소의 합은?`,
    answer:{ JAVA:["20"], PYTHON:["20"], CPP:["20"] },
    options:null, correctIndex:null,
    explanation:`2+4+6+8 = 20입니다.` },
  { id:`M11`, type:`fill_blank`, difficulty:`medium`, title:`배열 정렬`,
    question:`Arrays._____(arr); // Java 배열을 오름차순으로 정렬하는 메소드`,
    answer:{ JAVA:["sort"], PYTHON:["sorted"], CPP:["sort"] },
    options:null, correctIndex:null,
    explanation:`Arrays.sort()로 배열을 정렬합니다.` },
  { id:`M12`, type:`multiple_choice`, difficulty:`medium`, title:`최댓값`,
    question:`Math._____(3, 7, 2)의 결과는?`,
    answer:{ JAVA:["7"], PYTHON:["7"], CPP:["7"] },
    options:["3", "7", "2", "10"], correctIndex:1,
    explanation:`Math.max()는 최댓값을 반환합니다.` },
  { id:`M13`, type:`fill_blank`, difficulty:`medium`, title:`문자열 길이`,
    question:`String s = "hello";
int len = s._____(); // 문자열의 길이를 구하는 메소드`,
    answer:{ JAVA:["length"], PYTHON:["len"], CPP:["length"] },
    options:null, correctIndex:null,
    explanation:`length()/len()으로 문자열 길이를 구합니다.` },
  { id:`M14`, type:`multiple_choice`, difficulty:`medium`, title:`문자열 분할`,
    question:`"a,b,c".split(",")의 결과 길이는?`,
    answer:{ JAVA:["3"], PYTHON:["3"], CPP:["3"] },
    options:["2", "3", "4", "1"], correctIndex:1,
    explanation:`split()은 구분자로 문자열을 분할합니다.` },
  { id:`M15`, type:`fill_blank`, difficulty:`medium`, title:`문자열 인덱스`,
    question:`String s = "programming";
char c = s._____(0); // 0번째 문자를 가져오는 메소드`,
    answer:{ JAVA:["charAt"], PYTHON:["[0]"], CPP:["at"] },
    options:null, correctIndex:null,
    explanation:`charAt(인덱스)로 해당 위치 문자를 가져옵니다.` },
  { id:`M16`, type:`multiple_choice`, difficulty:`medium`, title:`List 추가`,
    question:`ArrayList에서 맨 끝에 요소를 추가하는 메소드는?`,
    answer:{ JAVA:["add"], PYTHON:["append"], CPP:["push_back"] },
    options:["insert", "append", "add", "push"], correctIndex:2,
    explanation:`Java의 ArrayList는 add()를 사용합니다.` },
  { id:`M17`, type:`fill_blank`, difficulty:`medium`, title:`List 크기`,
    question:`ArrayList<Integer> list = new ArrayList<>();
list.add(1); list.add(2);
int size = list._____(); // 리스트의 크기를 구하는 메소드`,
    answer:{ JAVA:["size"], PYTHON:["len"], CPP:["size"] },
    options:null, correctIndex:null,
    explanation:`size()로 컬렉션의 크기를 구합니다.` },
  { id:`M18`, type:`multiple_choice`, difficulty:`medium`, title:`문자열 포함`,
    question:`String s = "abcdef"; s.contains("cd")의 결과는?`,
    answer:{ JAVA:["true"], PYTHON:["True"], CPP:["true"] },
    options:["true", "false", "True", "False"], correctIndex:0,
    explanation:`contains()는 부분 문자열 포함 여부를 반환합니다.` },
  { id:`M19`, type:`fill_blank`, difficulty:`medium`, title:`문자열 변환`,
    question:`int num = 42;
String s = String._____(num); // 숫자를 문자열로 변환하는 메소드`,
    answer:{ JAVA:["valueOf"], PYTHON:["str"], CPP:["to_string"] },
    options:null, correctIndex:null,
    explanation:`valueOf() 또는 toString()으로 변환합니다.` },
  { id:`M20`, type:`multiple_choice`, difficulty:`medium`, title:`문자열 비교`,
    question:`Java에서 문자열 내용을 비교할 때 사용하는 메소드는?`,
    answer:{ JAVA:["equals"], PYTHON:["=="], CPP:["=="] },
    options:["==", "equals", "compare", "match"], correctIndex:1,
    explanation:`Java에서는 equals()로 내용을 비교합니다.` },
  { id:`X11`, type:`fill_blank`, difficulty:`medium`, title:`StringBuilder`,
    question:`StringBuilder sb = new StringBuilder();
sb._____("hello"); // 문자열을 끝에 추가하는 메소드`,
    answer:{ JAVA:["append"], PYTHON:["append"], CPP:["append"] },
    options:null, correctIndex:null,
    explanation:`append()로 문자열을 추가합니다.` },
  { id:`X12`, type:`multiple_choice`, difficulty:`medium`, title:`substring`,
    question:`"hello".substring(1, 3)의 결과는?`,
    answer:{ JAVA:["el"], PYTHON:["el"], CPP:["el"] },
    options:["el", "ell", "hel", "lo"], correctIndex:0,
    explanation:`substring(1,3)은 1번 인덱스부터 3번 전까지, 즉 "el"입니다.` },
  { id:`X13`, type:`fill_blank`, difficulty:`medium`, title:`toCharArray`,
    question:`String s = "abc";
char[] arr = s._____(); // 문자열을 문자 배열로 변환하는 메소드`,
    answer:{ JAVA:["toCharArray"], PYTHON:["list"], CPP:["c_str"] },
    options:null, correctIndex:null,
    explanation:`toCharArray()로 문자열을 char 배열로 변환합니다.` },
  { id:`X14`, type:`multiple_choice`, difficulty:`medium`, title:`indexOf`,
    question:`"banana".indexOf("na")의 결과는?`,
    answer:{ JAVA:["2"], PYTHON:["2"], CPP:["2"] },
    options:["1", "2", "3", "4"], correctIndex:1,
    explanation:`"na"가 처음 등장하는 인덱스는 2입니다.` },
  { id:`X15`, type:`fill_blank`, difficulty:`medium`, title:`trim`,
    question:`String s = "  hello  ";
String t = s._____(); // 양쪽 공백을 제거하는 메소드`,
    answer:{ JAVA:["trim"], PYTHON:["strip"], CPP:["trim"] },
    options:null, correctIndex:null,
    explanation:`trim()/strip()으로 양쪽 공백을 제거합니다.` },
  { id:`X16`, type:`multiple_choice`, difficulty:`medium`, title:`parseInt`,
    question:`Integer.parseInt("123")의 결과는?`,
    answer:{ JAVA:["123"], PYTHON:["123"], CPP:["123"] },
    options:["123", "\"123\"", "NaN", "오류"], correctIndex:0,
    explanation:`parseInt()는 문자열을 정수로 변환합니다.` },
  { id:`X17`, type:`fill_blank`, difficulty:`medium`, title:`Collections.sort`,
    question:`List<Integer> list = Arrays.asList(3,1,4);
Collections._____(list); // 리스트를 정렬하는 메소드`,
    answer:{ JAVA:["sort"], PYTHON:["sort"], CPP:["sort"] },
    options:null, correctIndex:null,
    explanation:`Collections.sort()로 List를 정렬합니다.` },
  { id:`X18`, type:`multiple_choice`, difficulty:`medium`, title:`Math.min`,
    question:`Math.min(10, 5, 8)의 결과는?`,
    answer:{ JAVA:["5"], PYTHON:["5"], CPP:["5"] },
    options:["10", "5", "8", "3"], correctIndex:1,
    explanation:`Math.min()은 최솟값을 반환합니다.` },
  { id:`X19`, type:`fill_blank`, difficulty:`medium`, title:`equalsIgnoreCase`,
    question:`String a = "Hello";
boolean same = a._____("hello"); // 대소문자 구분 없이 비교하는 메소드`,
    answer:{ JAVA:["equalsIgnoreCase"], PYTHON:["lower()=="], CPP:["strcasecmp"] },
    options:null, correctIndex:null,
    explanation:`equalsIgnoreCase()는 대소문자를 무시하고 비교합니다.` },
  { id:`X20`, type:`multiple_choice`, difficulty:`medium`, title:`replaceAll`,
    question:`"aabbaabb".replaceAll("a", "x")의 결과는?`,
    answer:{ JAVA:["xxbbxxbb"], PYTHON:["xxbbxxbb"], CPP:["xxbbxxbb"] },
    options:["xxbbxxbb", "xxbbaabb", "aabbaabb", "xxbbaaxb"], correctIndex:0,
    explanation:`replaceAll()은 모든 일치하는 문자열을 대체합니다.` },
  { id:`H01`, type:`multiple_choice`, difficulty:`hard`, title:`포인터 결과`,
    question:`C++에서 int a=10; int* p=&a; cout<<*p; 의 출력값은?`,
    answer:{ JAVA:["10"], PYTHON:["10"], CPP:["10"] },
    options:["10", "주소값", "a", "오류 발생"], correctIndex:0,
    explanation:`*p는 p가 가리키는 주소의 값을 반환합니다.` },
  { id:`H02`, type:`short_answer`, difficulty:`hard`, title:`2진수 변환`,
    question:`10진수 10을 2진수로 변환하면? (숫자만)`,
    answer:{ JAVA:["1010"], PYTHON:["1010"], CPP:["1010"] },
    options:null, correctIndex:null,
    explanation:`10 = 8+2 = 1010₂ 입니다.` },
  { id:`H03`, type:`multiple_choice`, difficulty:`hard`, title:`시간복잡도`,
    question:`버블 정렬의 평균 시간복잡도는?`,
    answer:{ JAVA:["O(n²)"], PYTHON:["O(n²)"], CPP:["O(n²)"] },
    options:["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], correctIndex:2,
    explanation:`버블 정렬은 이중 반복문으로 O(n²)입니다.` },
  { id:`H04`, type:`fill_blank`, difficulty:`hard`, title:`참조 반환`,
    question:`int& ref = x; ref = 5; // x의 값은? (숫자만)`,
    answer:{ JAVA:["5"], PYTHON:["5"], CPP:["5"] },
    options:null, correctIndex:null,
    explanation:`참조 변수 ref는 x의 별칭입니다.` },
  { id:`H05`, type:`multiple_choice`, difficulty:`hard`, title:`DFS 자료구조`,
    question:`그래프를 DFS로 방문할 때 사용하는 자료구조는?`,
    answer:{ JAVA:["Stack"], PYTHON:["스택"], CPP:["Stack"] },
    options:["Queue", "Stack", "Heap", "Array"], correctIndex:1,
    explanation:`DFS는 스택(또는 재귀호출)을 사용합니다.` },
  { id:`H06`, type:`short_answer`, difficulty:`hard`, title:`산술 결과`,
    question:`int a=7, b=3; a/b + a%b 의 결과값은? (숫자만)`,
    answer:{ JAVA:["3"], PYTHON:["3"], CPP:["3"] },
    options:null, correctIndex:null,
    explanation:`7/3=2, 7%3=1, 2+1=3 입니다.` },
  { id:`H07`, type:`multiple_choice`, difficulty:`hard`, title:`DP 핵심`,
    question:`동적계획법(DP)의 핵심 특징은?`,
    answer:{ JAVA:["Memoization"], PYTHON:["메모이제이션"], CPP:["Memoization"] },
    options:["분할정복", "메모이제이션", "백트래킹", "브루트포스"], correctIndex:1,
    explanation:`DP는 계산 결과를 저장(메모이제이션)하여 중복 계산을 피합니다.` },
  { id:`H08`, type:`short_answer`, difficulty:`hard`, title:`비트연산`,
    question:`5 & 3 의 결과값은? (비트 AND) (숫자만)`,
    answer:{ JAVA:["1"], PYTHON:["1"], CPP:["1"] },
    options:null, correctIndex:null,
    explanation:`5=101₂, 3=011₂, AND 결과는 001₂=1 입니다.` },
  { id:`H09`, type:`fill_blank`, difficulty:`hard`, title:`포인터 연산`,
    question:`int arr[] = {1,2,3}; cout << *(arr+1); // 출력값은? (숫자만)`,
    answer:{ JAVA:["2"], PYTHON:["2"], CPP:["2"] },
    options:null, correctIndex:null,
    explanation:`arr+1은 두번째 요소를 가리키며 값은 2입니다.` },
  { id:`H10`, type:`short_answer`, difficulty:`hard`, title:`정렬 결과`,
    question:`{3,1,4,1,5}를 버블정렬 1회전 후 배열은? (쉼표로 구분)`,
    answer:{ JAVA:["1,3,1,4,5"], PYTHON:["1,3,1,4,5"], CPP:["1,3,1,4,5"] },
    options:null, correctIndex:null,
    explanation:`1회전 시 가장 큰 5가 끝으로 이동합니다.` },
  { id:`H11`, type:`multiple_choice`, difficulty:`hard`, title:`이진탐색 전제`,
    question:`이진 탐색이 동작하려면 데이터가 어떤 상태여야 하나?`,
    answer:{ JAVA:["정렬된 상태"], PYTHON:["정렬된 상태"], CPP:["정렬된 상태"] },
    options:["정렬된 상태", "랜덤 상태", "역순 상태", "중복 없는 상태"], correctIndex:0,
    explanation:`이진 탐색은 정렬된 데이터에서만 사용할 수 있습니다.` },
  { id:`H12`, type:`short_answer`, difficulty:`hard`, title:`이진탐색 복잡도`,
    question:`이진 탐색의 시간복잡도는? (예: O(log n))`,
    answer:{ JAVA:["O(log n)"], PYTHON:["O(log n)"], CPP:["O(log n)"] },
    options:null, correctIndex:null,
    explanation:`탐색 범위를 절반씩 줄여 O(log n)입니다.` },
  { id:`H13`, type:`fill_blank`, difficulty:`hard`, title:`비트 시프트`,
    question:`1 << _____ 는 8이다. (숫자만)`,
    answer:{ JAVA:["3"], PYTHON:["3"], CPP:["3"] },
    options:null, correctIndex:null,
    explanation:`1을 3번 왼쪽 시프트하면 8입니다.` },
  { id:`H14`, type:`multiple_choice`, difficulty:`hard`, title:`BFS`,
    question:`무가중치 그래프에서 최단 경로를 찾을 때 사용하는 탐색은?`,
    answer:{ JAVA:["BFS"], PYTHON:["BFS"], CPP:["BFS"] },
    options:["DFS", "BFS", "DP", "Greedy"], correctIndex:1,
    explanation:`무가중치 그래프에서는 BFS가 최단 경로를 보장합니다.` },
  { id:`H15`, type:`short_answer`, difficulty:`hard`, title:`ASCII`,
    question:`문자 \`A\`의 ASCII 값은? (숫자만)`,
    answer:{ JAVA:["65"], PYTHON:["65"], CPP:["65"] },
    options:null, correctIndex:null,
    explanation:`대문자 A의 ASCII 코드는 65입니다.` },
  { id:`H16`, type:`fill_blank`, difficulty:`hard`, title:`모듈러`,
    question:`17 % 5 = _____ (숫자만)`,
    answer:{ JAVA:["2"], PYTHON:["2"], CPP:["2"] },
    options:null, correctIndex:null,
    explanation:`17 = 15 + 2 이므로 나머지는 2입니다.` },
  { id:`H17`, type:`multiple_choice`, difficulty:`hard`, title:`키-값 저장`,
    question:`키-값 쌍을 저장하는 자료구조는?`,
    answer:{ JAVA:["HashMap"], PYTHON:["dict"], CPP:["map"] },
    options:["Stack", "Queue", "Map", "Array"], correctIndex:2,
    explanation:`HashMap/dict/map은 키-값 쌍을 저장합니다.` },
  { id:`H18`, type:`short_answer`, difficulty:`hard`, title:`스택 오버플로우`,
    question:`재귀 호출이 너무 깊어질 때 발생하는 오류는? (영문)`,
    answer:{ JAVA:["stack overflow"], PYTHON:["stack overflow"], CPP:["stack overflow"] },
    options:null, correctIndex:null,
    explanation:`호출 스택이 넘치면 StackOverflowError가 발생합니다.` },
  { id:`H19`, type:`fill_blank`, difficulty:`hard`, title:`비트 AND`,
    question:`5 & 3 = _____ (숫자만)`,
    answer:{ JAVA:["1"], PYTHON:["1"], CPP:["1"] },
    options:null, correctIndex:null,
    explanation:`5=101, 3=011, AND 결과는 001=1입니다.` },
  { id:`H20`, type:`multiple_choice`, difficulty:`hard`, title:`DP 핵심`,
    question:`동적계획법의 핵심은?`,
    answer:{ JAVA:["중복 계산 저장"], PYTHON:["중복 계산 저장"], CPP:["중복 계산 저장"] },
    options:["중복 계산 저장", "무한 반복", "랜덤 탐색", "파일 입출력"], correctIndex:0,
    explanation:`중복 계산을 저장해 재사용합니다.` },
  { id:`X21`, type:`multiple_choice`, difficulty:`hard`, title:`퀵정렬 평균`,
    question:`퀵 정렬의 평균 시간복잡도는?`,
    answer:{ JAVA:["O(n log n)"], PYTHON:["O(n log n)"], CPP:["O(n log n)"] },
    options:["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], correctIndex:1,
    explanation:`퀵 정렬의 평균 시간복잡도는 O(n log n)입니다.` },
  { id:`X22`, type:`short_answer`, difficulty:`hard`, title:`힙`,
    question:`최소값을 O(1)에 조회할 수 있는 자료구조는? (영문)`,
    answer:{ JAVA:["heap"], PYTHON:["heap"], CPP:["heap"] },
    options:null, correctIndex:null,
    explanation:`Min-Heap은 루트에 최소값이 있어 O(1) 조회가 가능합니다.` },
  { id:`X23`, type:`fill_blank`, difficulty:`hard`, title:`다익스트라`,
    question:`양의 가중치 그래프에서 최단 경로를 찾는 알고리즘은 _____ 알고리즘이다.`,
    answer:{ JAVA:["Dijkstra"], PYTHON:["Dijkstra"], CPP:["Dijkstra"] },
    options:null, correctIndex:null,
    explanation:`다익스트라 알고리즘은 양의 가중치 그래프에서 사용됩니다.` },
  { id:`X24`, type:`multiple_choice`, difficulty:`hard`, title:`O(1) 접근`,
    question:`임의의 인덱스에 O(1)로 접근 가능한 자료구조는?`,
    answer:{ JAVA:["Array"], PYTHON:["Array"], CPP:["Array"] },
    options:["LinkedList", "Array", "Tree", "Stack"], correctIndex:1,
    explanation:`배열은 인덱스를 통한 O(1) 임의 접근이 가능합니다.` },
  { id:`X25`, type:`fill_blank`, difficulty:`hard`, title:`우선순위 큐`,
    question:`PriorityQueue는 _____ 자료구조를 기반으로 구현된다.`,
    answer:{ JAVA:["Heap"], PYTHON:["Heap"], CPP:["Heap"] },
    options:null, correctIndex:null,
    explanation:`PriorityQueue는 힙(Heap)을 기반으로 합니다.` },
  { id:`X26`, type:`multiple_choice`, difficulty:`hard`, title:`Set 특징`,
    question:`HashSet의 특징은?`,
    answer:{ JAVA:["중복 불가"], PYTHON:["중복 불가"], CPP:["중복 불가"] },
    options:["중복 가능", "중복 불가", "정렬 보장", "순서 보장"], correctIndex:1,
    explanation:`HashSet은 중복을 허용하지 않습니다.` },
  { id:`X27`, type:`fill_blank`, difficulty:`hard`, title:`인터페이스 구현`,
    question:`class MyList _____ List { ... } // 인터페이스를 구현할 때 사용하는 키워드`,
    answer:{ JAVA:["implements"], PYTHON:["(List)"], CPP:[": public"] },
    options:null, correctIndex:null,
    explanation:`Java는 implements, Python은 상속, C++은 : public을 사용합니다.` },
  { id:`X28`, type:`multiple_choice`, difficulty:`hard`, title:`AVL 트리`,
    question:`AVL 트리는 어떤 성질을 만족하는 이진 탐색 트리인가?`,
    answer:{ JAVA:["균형"], PYTHON:["균형"], CPP:["균형"] },
    options:["균형", "완전", "포화", "이상"], correctIndex:0,
    explanation:`AVL 트리는 균형 이진 탐색 트리입니다.` },
  { id:`X29`, type:`fill_blank`, difficulty:`hard`, title:`Comparator`,
    question:`Collections.sort(list, new _____() { ... }); // 정렬 기준을 커스텀하게 지정하는 인터페이스`,
    answer:{ JAVA:["Comparator"], PYTHON:["key"], CPP:["compare"] },
    options:null, correctIndex:null,
    explanation:`Comparator 인터페이스로 정렬 기준을 정의합니다.` },
  { id:`X30`, type:`multiple_choice`, difficulty:`hard`, title:`플로이드-워셜`,
    question:`모든 쌍 최단 경로를 구하는 알고리즘은?`,
    answer:{ JAVA:["Floyd-Warshall"], PYTHON:["Floyd-Warshall"], CPP:["Floyd-Warshall"] },
    options:["Dijkstra", "Floyd-Warshall", "Prim", "Kruskal"], correctIndex:1,
    explanation:`Floyd-Warshall은 모든 정점 쌍 간 최단 경로를 구합니다.` },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = problems;
}